<?php

namespace GatherUp\Providers;

use GatherUp\Models\Team;
use GatherUp\Validation\TeamValidation;
use Validator;
use Laravel\Spark\Spark;
use Illuminate\Http\Request;
use Laravel\Spark\Providers\AppServiceProvider as ServiceProvider;

class SparkServiceProvider extends ServiceProvider
{
    /**
     * Meta-data included in invoices generated by Spark.
     *
     * @var array
     */
    protected $invoiceWith = [
        'vendor' => 'The Julie Ann Wrigley Global Institute of Sustainability',
        'product' => 'Gather Up',
        'street' => '800 South Cady Mall',
        'location' => 'Tempe, AZ 85281',
        'phone' => '480-965-2975',
    ];

    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        parent::boot();

        //
    }

    /**
     * Customize general Spark options.
     *
     * @return void
     */
    protected function customizeSpark()
    {
        Spark::configure([
            'models' => [
                'teams' => Team::class,
            ]
        ]);

        // Make sure users can make teams
        Spark::validateNewTeamsWith(function() {
            return (new TeamValidation())->validateNewTeamsWith();
        });
    }

    /**
     * Customize Spark's new user registration logic.
     *
     * @return void
     */
    protected function customizeRegistration()
    {
        // Spark::validateRegistrationsWith(function (Request $request) {
        //     return [
        //         'name' => 'required|max:255',
        //         'email' => 'required|email|unique:users',
        //         'password' => 'required|confirmed|min:6',
        //         'terms' => 'required|accepted',
        //     ];
        // });

        // Spark::validateSubscriptionsWith(function (Request $request) {
        //     return [
        //         'plan' => 'required',
        //         'terms' => 'required|accepted',
        //         'stripe_token' => 'required',
        //     ];
        // });

        // Spark::createUsersWith(function (Request $request) {
        //     // Return New User Instance...
        // });
    }

    /**
     * Customize the roles that may be assigned to team members.
     *
     * @return void
     */
    protected function customizeRoles()
    {
        Spark::defaultRole('member');

        Spark::roles([
            'admin' => 'Administrator',
            'member' => 'Member',
        ]);
    }

    /**
     * Customize the tabs on the settings screen.
     *
     * @return void
     */
    protected function customizeSettingsTabs()
    {
        Spark::settingsTabs()->configure(function ($tabs) {
            return [
                $tabs->profile(),
                $tabs->teams(),
                $tabs->security(),
                $tabs->subscription(),
                // $tabs->make('Name', 'view', 'fa-icon'),
            ];
        });

        Spark::teamSettingsTabs()->configure(function ($tabs) {
            return [
                $tabs->owner(),
                $tabs->membership(),
                // $tabs->make('Name', 'view', 'fa-icon'),
            ];
        });
    }

    /**
     * Customize Spark's profile update logic.
     *
     * @return void
     */
    protected function customizeProfileUpdates()
    {
        // Spark::validateProfileUpdatesWith(function (Request $request) {
        //     return [
        //         'name' => 'required|max:255',
        //         'email' => 'required|email|unique:users,email,'.$request->user()->id,
        //     ];
        // });

        // Spark::updateProfilesWith(function (Request $request) {
        //     // Update $request->user()...
        // });
    }

    /**
     * Customize the subscription plans for the application.
     *
     * @return void
     */
    protected function customizeSubscriptionPlans()
    {
        // Monthly plans
        Spark::free('Individual')
            ->features([
                'Web forms',
                '5 events per month',
                'Unlimited sign ups',
                'Salesforce integration',
            ]);

        Spark::plan('Basic', config('services.stripe.plans.basic_monthly_plan_id'))->price(100)
            ->features([
                'Android, iOS, and Web forms',
                'Unlimited events',
                'Unlimited sign ups',
                'Salesforce integration',
                'Single team',
            ]);

        Spark::plan('Premium', 'todo-stripe-plan-id')->price(500)
            ->features([
                'Android, iOS, and Web forms',
                'Unlimited events',
                'Unlimited sign ups',
                'Salesforce integration',
                'Multiple teams',
                'Theme customization',
            ]);

        // Yearly plans
        Spark::plan('Basic', 'todo-stripe-plan-id')->price(12 * 80)
            ->yearly()
            ->features([
                'Android, iOS, and Web forms',
                'Unlimited events',
                'Unlimited sign ups',
                'Salesforce integration',
                'Single department',
            ]);

        Spark::plan('Premium', 'todo-stripe-plan-id')->price(12 * 400)
            ->yearly()
            ->features([
                'Android, iOS, and Web forms',
                'Unlimited events',
                'Unlimited sign ups',
                'Salesforce integration',
                'Multiple departments',
                'Theme customization',
            ]);
    }
}
